"""Regenerate the checked-in native SDK layout manifest with Clang's AST.

The game builds the manifest with its own compiler. Clang is only required
when updating this list, not to build or use Portable.
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
import json
from pathlib import Path
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("--clang", default="C:/Program Files/LLVM/bin/clang-cl.exe")
parser.add_argument("--sdl-include", required=True)
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
types = [
    "LawnApp", "Sexy::SexyApp", "Sexy::SexyAppBase", "Sexy::Widget", "Sexy::WidgetContainer",
    "Sexy::ButtonListener", "Sexy::WidgetManager", "Board", "Challenge", "CutScene",
    "CursorObject", "CursorPreview", "SeedBank", "SeedPacket", "SeedChooserScreen", "ChosenSeed",
    "TitleScreen", "PlayerInfo", "PottedPlant", "ZenGarden", "ChallengeScreen", "GameObject",
    "Plant", "Zombie", "Projectile", "Coin", "GridItem", "LawnMower", "Reanimation",
    "PvzpParticleSystem", "PvzpNative::RandomState", "PvzpNative::ModifierState",
    "PvzpSmoothArray", "ChallengeDefinition", "SpecialGridPlacement", "PvzpPlugin::Host",
    "GameButton", "GameSelector", "Music", "Sexy::SoundManager", "Sexy::SoundInstance",
]

def describe(name):
    command = [args.clang, "/std:c++20", "/utf-8", "/MD", "/EHsc", "-fsyntax-only",
               "-x", "c++", "src/PvzpLib/PluginLayoutTypes.h", "/Isrc", "/Isrc/SexyAppFramework",
               "/Isrc/SexyAppFramework/sound/SDL-Mixer-X/include", "/I" + args.sdl_include,
               "-Xclang", "-ast-dump=json", "-Xclang", "-ast-dump-filter=" + name]
    result = subprocess.run(command, cwd=root, text=True, encoding="utf-8", errors="replace", capture_output=True)
    if result.returncode:
        raise RuntimeError(result.stderr)
    decoder, offset, objects = json.JSONDecoder(), 0, []
    while offset < len(result.stdout):
        while offset < len(result.stdout) and result.stdout[offset].isspace():
            offset += 1
        if offset == len(result.stdout):
            break
        value, offset = decoder.raw_decode(result.stdout, offset)
        objects.append(value)
    records = [o for o in objects if o.get("kind") == "CXXRecordDecl"
               and o.get("completeDefinition") and o.get("name") == name.split("::")[-1]]
    assert len(records) == 1, (name, len(records))
    record = records[0]
    access = "public" if record.get("tagUsed") == "struct" else "private"
    fields = []
    for child in record.get("inner", []):
        if child["kind"] == "AccessSpecDecl":
            access = child["access"]
        elif child["kind"] == "FieldDecl" and child.get("name") and access == "public":
            assert not child.get("isBitfield"), (name, child["name"])
            fields.append(child["name"])
    bases = [base["type"].get("desugaredQualType", base["type"]["qualType"]) for base in record.get("bases", [])]
    return name, fields, bases

with ThreadPoolExecutor(max_workers=4) as executor:
    records = list(executor.map(describe, types))
lines = ["// Generated by tools/generate-plugin-layout.py; build evaluates these with the EXE compiler."]
for name, fields, bases in records:
    lines.append(f"PVZP_LAYOUT_TYPE({name})")
    lines.extend(f"PVZP_LAYOUT_BASE({name}, {base})" for base in bases)
    lines.extend(f"PVZP_LAYOUT_FIELD({name}, {field})" for field in fields)
for entity in ["Plant", "Zombie", "Projectile", "Coin", "GridItem", "LawnMower"]:
    lines.append(f"PVZP_LAYOUT_POOL({entity})")
(root / "src/PvzpLib/PluginLayoutFields.inc").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Generated {len(lines)-1} layout declarations for {len(records)} objects and six pools")
